passwordreset/urls.py
'''
Created on Apr 07, 2014

@author: rkhapare
'''
##################################################################################################################
from django.conf.urls import *

##################################################################################################################
urlpatterns = patterns('members.views',
                        url(r'^$', 'login_view'),
#                         url('^signin/$', 'login_view'),
                        url('^blank/$', 'blank_view'),
                        url('^logout/$', 'logout_view'),
                        url('^signup/$', 'signup_view'),
                        url('^captcha/$', 'captcha_view'),
                        url('^otpgen/$', 'generate_otp_view'),
                        url('^otpvfy/$', 'verify_otp_view'),
                        url('^secque/$', 'furnish_securityQs_view'),
                        url('^repwd/$', 'change_password_view'),
)
##################################################################################################################

members/models.py
'''
Created on Apr 06, 2014

@author: rkhapare
'''
##################################################################################################################
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields.related import ForeignKey

##################################################################################################################
class Member(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    phone_no = models.CharField(max_length=13, blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)

##################################################################################################################    
class SecurityQuestions(models.Model):
    question = models.CharField(max_length=500, blank=False, null=False)
    
    def __unicode__(self):
        return u'%s' % (self.question)
    
##################################################################################################################
class MemberAnswers(models.Model):
    member = ForeignKey('Member', null=False)
    question = ForeignKey('SecurityQuestions', null=False)
    answer = models.CharField(max_length=20, blank=False, null=False)
    
    def __unicode__(self):
        return u'%s' % (self.answer)
    
##################################################################################################################

members/forms.py
'''
Created on Apr 7, 2014

@author: Rohit
'''
###################################################################################################################
from django import forms
from captcha.fields import ReCaptchaField
from members.models import Member, MemberAnswers, SecurityQuestions
import datetime
from django.forms.extras.widgets import SelectDateWidget
from django.contrib.auth.models import User

##################################################################################################################
class MemberLoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'password')
        widgets = {
           'password': forms.PasswordInput(),
        }
        
    def clean(self):
        cleaned_data = super(MemberLoginForm, self).clean()
        
        username = cleaned_data.get("username", None)
        password = cleaned_data.get("password", None)
        
        if not username:
            self._errors["username"] = self.error_class(["Please enter your username"])
            
        if not password:
            self._errors["password"] = self.error_class(["Please enter your password"])
            
        return cleaned_data

##################################################################################################################        
class MemberSignupForm1(forms.ModelForm):
    address = forms.CharField(widget=forms.Textarea(attrs={'cols': 32, 'rows': 5}))
    
    class Meta:
        model = Member
        exclude = ('user',)
        thisyear = datetime.datetime.now().year 
        widgets = {
            'dob': SelectDateWidget(years=range(thisyear-10, thisyear-60, -1)),
        }
    
    def clean(self):
        cleaned_data = super(MemberSignupForm1, self).clean()
        
        address = cleaned_data.get("address")
        dob = cleaned_data.get("dob")
                
        if not address:
            self._errors["address"] = self.error_class(["Please enter your address"])
        
        if not dob:
            self._errors["dob"] = self.error_class(["Please enter your birth date"])
            
        return cleaned_data
        
##################################################################################################################        
class MemberSignupForm2(forms.Form):
    username = forms.CharField(max_length=30, required=True)
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(), required=True)
    repassword = forms.CharField(max_length=30, widget=forms.PasswordInput(), required=True)
    email = forms.EmailField(max_length=75)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=False)
    
    class Meta:
        model = User
        fields = ('username', 'password', 'email', 'first_name', 'last_name')
        widgets = {
            'password': forms.PasswordInput(),
        }
        
    def clean(self):
        cleaned_data = super(MemberSignupForm2, self).clean()
        
        email = cleaned_data.get("email")
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        repassword = cleaned_data.get("repassword")
        first_name = cleaned_data.get("first_name")
        
        if not email:
            self._errors["email"] = self.error_class(["Please enter your email address for communication. It will never be shared/published"])
            
        if not username:
            self._errors["username"] = self.error_class(["Please enter your username"])
            
        if not password:
            self._errors["password"] = self.error_class(["Please enter your password"])
        
        if not repassword:
            self._errors["repassword"] = self.error_class(["Please enter the same password again"])
        
        if not password == repassword:
            self._errors["repassword"] = self.error_class(["Entered passwords do not match"])
            
        if not first_name:
            self._errors["first_name"] = self.error_class(["Please enter your first name for external communication. It will never be shared/published"])
            
        return cleaned_data
    
##################################################################################################################        
class SecurityQuestionAnswerForm(forms.Form):
    que1 = forms.ModelChoiceField(queryset=SecurityQuestions.objects.all(), required=True)
    que2 = forms.ModelChoiceField(queryset=SecurityQuestions.objects.all(), required=True)
    que3 = forms.ModelChoiceField(queryset=SecurityQuestions.objects.all(), required=True)
    ans1 = forms.CharField(max_length=20, required=True)
    ans2 = forms.CharField(max_length=20, required=True)
    ans3 = forms.CharField(max_length=20, required=True)
    
    def clean(self):
        cleaned_data = super(SecurityQuestionAnswerForm, self).clean()
        
        que1 = cleaned_data["que1"]
        ans1 = cleaned_data["ans1"]
        que2 = cleaned_data["que2"]
        ans2 = cleaned_data["ans2"]
        que3 = cleaned_data["que3"]
        ans3 = cleaned_data["ans3"]
        
        if que1 == que2 and que1 == que3:
            self._errors["que2"] = self.error_class(["Please select a different Security Question in this field"])
            self._errors["que3"] = self.error_class(["... and in this one too."])
        
        else:
            if que1 == que2:
                self._errors["que1"] = self.error_class(["Please select a different Security Question in this field"])
                self._errors["que2"] = self.error_class(["... or in this one."])
            
            if que1 == que3:
                self._errors["que1"] = self.error_class(["Please select a different Security Question in this field"])
                self._errors["que3"] = self.error_class(["... or in this one."])
            
            if que2 == que3:
                self._errors["que2"] = self.error_class(["Please select a different Security Question in this field"])
                self._errors["que3"] = self.error_class(["... or in this one."])
            
        return cleaned_data

###################################################################################################################
class CaptchaVerificationForm(forms.Form):
    captcha = ReCaptchaField()

##################################################################################################################
class OTPGenerationForm(forms.Form):
    email = forms.EmailField(max_length=75, required=False)
    phone = forms.CharField(max_length=13, required=False)
    
    def clean(self):
        cleaned_data = super(OTPGenerationForm, self).clean()
        
        email = cleaned_data.get("email")
        phone = cleaned_data.get("phone")
        
        if not email and not phone:
            self._errors["email"] = self.error_class(["Please enter your email address/phone for receiving One Time Password."])
            
        return cleaned_data

##################################################################################################################
class OTPVerificationForm(forms.Form):
    otp = forms.CharField(max_length=5, required=True)
    
##################################################################################################################
class SecurityQuestionForm(forms.ModelForm):
    answer = forms.CharField(max_length=20, required=True)
    
    class Meta:
        model = MemberAnswers
        exclude = ('member', 'question',)

##################################################################################################################
class ResetPasswordForm(forms.Form):
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(), required=True)
    repassword = forms.CharField(max_length=30, widget=forms.PasswordInput(), required=True)
    
    class Meta:
        model = User
        fields = ('password', )
        widgets = {
            'password': forms.PasswordInput(),
        }
        
    def clean(self):
        cleaned_data = super(ResetPasswordForm, self).clean()
        
        password = cleaned_data.get("password")
        repassword = cleaned_data.get("repassword")
        
        if not password:
            self._errors["password"] = self.error_class(["Please enter your password"])
        
        if not repassword:
            self._errors["repassword"] = self.error_class(["Please enter the same password again"])
        
        if not password == repassword:
            self._errors["repassword"] = self.error_class(["Entered passwords do not match"])
            
        return cleaned_data
    
################################################################################################################## 

passwordreset/templates/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="UTF-8" />

<title>{% block title %}{% endblock %}</title>
<!-- <link rel="stylesheet" type="text/css" href= "{% static "assets/css/base.css" %}" />

<script src="{% static "assets/js/jquery-2.0.0.min.js" %}" ></script>
<script src="{% static "assets/js/ajax.js" %}" ></script>-->

{% block extra_head %}    
	<script type="text/javascript">
    function validateFields(i)
    {
      if(i ==0){
        var regex_test = /^[a-z0-9_-]{3,15}$/;
        return regex_test.test(login_form.usernameText.value);
      }
      else if(i == 1)  
      {
        var regex_test = /^((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#_$%]).{6,20})$/;
        return regex_test.test(login_form.passwordText.value);
      }
      else 
      {
          var regex_test = /^[a-z0-9_-]{3,15}$/;
          var regex_test = /^((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#_$%]).{6,20})$/;
          return regex_test.test(login_form.usernameText.value) && regex_test.test(login_form.passwordText.value);
      }
    }
    </script>
    
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        padding-right: 40px;
        padding-left: 40px;
        background-color: #ffffff;
      }

      .login-form {
        max-width: 300px;
        padding: 20px 30px 30px;
        margin: 0 auto 20px;
        background-color: #ffffff;
        border: 2px solid #000000;
        -webkit-border-radius: 8px;
           -moz-border-radius: 8px;
                border-radius: 8px;

      }
      .login-form .login-form-heading {
        margin-bottom: 10px;
      }
      .login-form input[type="text"],
      .login-form input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        position: relative;

        padding-top: 5px;
        padding-bottom: 5px;
        padding-right: 0px;
        padding-left: 0px;
        border-color:#000000;
      }
    </style>
{% endblock %}
</head>
<body>
	<div class="first">
		<div class="site_title">
			Self Service Password Reset System {% block page_id %}{% endblock %}
		</div>
	</div>
		
	{% block content %}{% endblock %} 
	
	{% block footer %}
		<hr>
		<div id="templatemo_footer"> Copyright © sortmeout will never disclose any information you share here, 
		including your username, with any person, party or organization not authorized to work on your request on our behalf.</div>
	{% endblock %}
</body>
</html>

passwordreset/templates/blank.html
{% extends "base.html" %}

{% block title %}Member Succesful Signin{% endblock %}

{% block page_id %}- Blank Page{% endblock %}

{% block content %}
	Hello {{ mFn }}. There is really nothing to be done here. Yeah really really -.-
    <button class="buttons" type="button"><a href="{% url 'members.views.logout_view'%}" class="nodec">log(me)out</a></button>
{% endblock %}

passwordreset/templates/forgot_password_step_1.htm
{% extends "base.html" %}

{% block title %}Member Validation{% endblock %}

{% block page_id %}- Forgot Password - Step 1 of 3{% endblock %}

{% block content %}
    <div class="container">
      <form class="login-form" name="login_form" method="POST">
		{% csrf_token %}
        <h3 class="login-form-heading">Let's find out if you are human, at all ...</h3>
          
        {{ form.non_field_errors }}

		<table border="0">
		  	<tr>
		    	<label for="id_username">Enter the text shown in the image below.</label>
	      	</tr>
		  
		  	<tr>
		  		{{ form.captcha }}
	      	</tr>
	      	
	      	{% if form.captcha.errors %}
	      		<tr>
	      			{{ form.captcha.errors }}
	      		</tr>
	      	{% endif %}
  		</table>
	
    	<p><input class="buttons" id="id_validate" type="submit" value="validate" name="keypress" /></p>
               
      </form>
    </div> 
{% endblock %}

passwordreset/templates/forgot_password_step_2_1.htm
{% extends "base.html" %}

{% block title %}Member Validation{% endblock %}

{% block page_id %}- Forgot Password - Step 2 of 3{% endblock %}

{% block content %}
    <div class="container">
      <form class="login-form" name="forgot_password_step2_1" method="POST">
      	{% csrf_token %}
        <h3 class="login-form-heading">Let's warm up a bit before the final test ...</h3>
        
        {{ form.non_field_errors }}

        <table border="0">
		  	<tr>
		    	<td width="20px"><label for="id_email">Registered Email Addr.</label></td>
		    	<td width="5px">:</td>
		    	<td >{{ form.email }}</td>
		    	<td >{{ form.email.errors }}</td>
	      	</tr>
	      	
	      	<tr>
		    	<td>OPTIONALLY ...</td>
		    	<td></td>
		    	<td></td>
		    	<td></td>
	      	</tr>
		  
		  	<tr>
		    	<td><label for="id_phone">Registered Phone No.</label></td>
		    	<td>:</td>
		    	<td>{{ form.phone }}</td>
		    	<td>{{ form.phone.errors }}</td>
	      	</tr>
  		</table>
	
    	<p><input class="buttons" id="id_validate" type="submit" value="Send OTP" name="keypress" /></p>     
      </form>
    </div> 
{% endblock %}

passwordreset/templates/forgot_password_step_2_2.htm
{% extends "base.html" %}

{% block title %}Member Validation{% endblock %}

{% block page_id %}- Forgot Password - Step 2 of 3{% endblock %}

{% block content %}
    <div class="container">
      <form class="login-form" name="forgot_password_step2_2" method="POST">
      	{% csrf_token %}
        <h3 class="login-form-heading">Ready ... Steady ... OTP ...</h3>
        
        {{ form.non_field_errors }}

        <table border="0">
		  	<tr>
		    	<td width="20px"><label for="id_email">{% if mFn %}{{ mFn }}'s {% endif %}OTP</label></td>
		    	<td width="5px">:</td>
		    	<td >{{ form.otp }}</td>
		    	<td >{{ form.otp.errors }}</td>
	      	</tr>
  		</table>
	
    	<p><input class="buttons" id="id_validate" type="submit" value="Verify OTP" name="keypress" /></p>     
      </form>
    </div> 
{% endblock %}

passwordreset/templates/forgot_password_step_3.htm
{% extends "base.html" %}

{% block title %}Member Signin{% endblock %}

{% block page_id %}- Forgot Password - Step 3 of 3{% endblock %}

{% block content %}
    <div class="container">

      <form class="login-form" name="forgot_password_step3" method="POST">
      	{% csrf_token %}
        <h3 class="login-form-heading">Let's see how much you know about yourself ... yeah LOL</h3>
        
        <table border="0">
		  	<tr><label for="id_question">{{ que }}</label></tr>
		    <tr>{{ form.answer }}</tr>
		    {% if form.answer.errors %}
		    	<tr>{{ form.answer.errors }}</tr>
		    {% endif %}
  		</table>
        
        <p><input class="buttons" id="id_answer" type="submit" value="submit" name="keypress" /></p> 
        <!-- <input type="label" name ="label1" value="Security Question 1:"></input><br />
        <input type="text" name="text1" placeholder="security answer 1"><br />
        <input type="label" name ="label2" value="Security Question 2:"></input><br />
        <input type="text" name="text2" placeholder="security answer 2"><br /> 
        <input type="label" name ="label3" value="Security Question 3:"></input><br />
        <input type="text" name="text3" placeholder="security answer 3"><br /> 
        <button  type="button" onclick="location.href='forgot_password_step_3.htm'">Go to the Final step</button> <br /><br /> -->        
      </form>

    </div> 
{% endblock %}

passwordreset/templates/forgot_username.htm
<!DOCTYPE html>
<html><head>
    <title>Self Service Password Reset System - Forgot Username</title>
    <script type="text/javascript">
    function validateEmail(email) { 
      var regexString = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
       if(regexString.test(forgot_username.emailText.value) == false)
       {
          return false;
       }
       else
       {
          return true;
       }
    } 
    </script>
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        padding-right: 40px;
        padding-left: 40px;
        background-color: #ffffff;
      }

      .forgot_username {
        max-width: 300px;
        padding: 20px 30px 30px;
        margin: 0 auto 20px;
        background-color: #ffffff;
        border: 2px solid #000000;
        -webkit-border-radius: 8px;
           -moz-border-radius: 8px;
                border-radius: 8px;

      }
      .forgot_username .forgot_username-heading {
        margin-bottom: 10px;
      }
      .forgot_username input[type="text"]
      {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        position: relative;
        

        padding-top: 5px;
        padding-bottom: 5px;
        padding-right: 0px;
        padding-left: 0px;
        border-color:#000000;
      }

    </style>
  </head>

  <body>

    <div class="container">

      <form class="forgot_username" name="forgot_username">
        <h2 class="forgot_username-heading">Forgot Username</h2>
        <input type="text" name="emailText" placeholder="Enter your email id" onblur="validateEmail(emailText.text)">
        <button  type="button" onclick="if(validateEmail(emailText.text) == false) { alert('Invalid email entered. Please try agian.'); }
        else{location.href='success.htm';}">Recover Username</button> <br /><br />
      </form>
    </div> 
</body></html>

passwordreset/templates/login.html
{% extends "base.html" %}

{% block title %}Member Signin{% endblock %}

{% block page_id %}- Signin Page{% endblock %}

{% block content %}
    <div class="container">
      <form class="login-form" name="login_form"method="POST">
		{% csrf_token %}
        <h3 class="login-form-heading">Log In</h3>
        <!--<input type="text" placeholder="Username" name="usernameText" onblur="if(validateFields(0) == false) { alert('Invalid Username. ');}">
        <input type="password" placeholder="Password" name="passwordText" onblur="if(validateFields(1) == false) { alert('Password entered does not meet the requirements.It should contain: \n\r 1 letter in lower case\n\r 1 letter in upper case\n\r 1 special character from the @, #, _, $ and %. \n\rThe length must be at least 6 characters upto 20 characters.');}"> 
        <button  type="button" id="submit" onclick="if(validateFields(2) == false){alert('Invalid Username or password entered.')}" >Log in</button> <br /><br />
        <button  type="button" id="forgot_username" onclick="location.href='forgot_username.htm'" size=15>Forgot Username</button>
        <button  type="button" id="forgot_password" onclick="location.href='forgot_password_step_1.htm'">Forgot Password</button>-->
        
        {{ form.non_field_errors }}
        {% if message %}{{ message }}{% endif %}

		<table border="0">
		  	<tr>
		    	<td width="20px"><label for="id_username">(Me)username</label></td>
		    	<td width="5px">:</td>
		    	<td >{{ form.username }}</td>
		    	<td >{{ form.username.errors }}</td>
	      	</tr>
		  
		  	<tr>
		    	<td><label for="id_password">(Me)password</label></td>
		    	<td>:</td>
		    	<td>{{ form.password }}</td>
		    	<td>{{ form.password.errors }}</td>
	      	</tr>
  		</table>
	
    	<p>
			<input  class="buttons" id="id_submit" type="submit" value="log(me)in" name="keypress" />
			<input  class="buttons" id="id_password" type="submit" value="sign(me)up" name="keypress" />
		</p><p>
			<!-- <input  class="buttons" id="id_forgot_username" type="submit" value="forgot(my)username" name="keypress" /> -->
			<input  class="buttons" id="id_forgot_password" type="submit" value="forgot(my)password" name="keypress" />
		</p>
      </form>

    </div> 
{% endblock %}

passwordreset/templates/registration.html
{% extends "base.html" %}

{% block title %}new member signup{% endblock %}

{% block page_id %}- Signup Page{% endblock %}

{% block content %}
<form action="" method="POST">
{% csrf_token %}
	<p>
		{{ form1.non_field_errors }}
		{{ form2.non_field_errors }}
		
		<table width="100%" border="0">
  			<tr>
    			<td width="11%"><label for="id_firstname">First Name *</label></td>
    			<td width="1%" >:</td>
    			<td width="21%">{{ form2.first_name }}</td>
    			<td width="67%">{{ form2.first_name.errors }}</td>
  			</tr>

 			<tr>
    			<td><label for="id_lastname">Last Name</label></td>
    			<td>:</td>
    			<td>{{ form2.last_name }}</td>
			    <td>{{ form2.last_name.errors }}</td>
 			</tr>
  
  			<tr>
    			<td><label for="id_dob">Birth Date *</label></td>
    			<td>:</td>
    			<td>{{ form1.dob }}</td>
    			<td>{{ form1.dob.errors }}</td>
  			</tr>
  			
  			<tr>
    			<td><label for="id_address">Address *</label></td>
    			<td>:</td>
    			<td>{{ form1.address }}</td>
    			<td>{{ form1.address.errors }}</td>
  			</tr>
  			
  			<tr>
    			<td><label for="id_email">Email Address *</label></td>
    			<td>:</td>
    			<td>{{ form2.email }}</td>
    			<td>{{ form2.email.errors }}</td>
  			</tr>
  			
  			<tr>
    			<td><label for="id_phone_no">Contact Number</label></td>
    			<td>:</td>
    			<td>{{ form1.phone_no }}</td>
    			<td>{{ form1.phone_no.errors }}</td>
  			</tr>
  			
  			<tr>
    			<td><label for="id_que1">Question 1 *</label></td>
    			<td>:</td>
    			<td>{{ form3.que1 }}</td>
    			<td>{{ form3.que1.errors }}</td>
  			</tr>
  			
  			<tr>
    			<td><label for="id_ans1">Answer 1 *</label></td>
    			<td>:</td>
    			<td>{{ form3.ans1 }}</td>
    			<td>{{ form3.ans1.errors }}</td>
  			</tr>

 			<tr>
    			<td><label for="id_que2">Question 2 *</label></td>
    			<td>:</td>
    			<td>{{ form3.que2 }}</td>
			    <td>{{ form3.que2.errors }}</td>
 			</tr>
 			
 			<tr>
    			<td><label for="id_ans1">Answer 2 *</label></td>
    			<td>:</td>
    			<td>{{ form3.ans2 }}</td>
    			<td>{{ form3.ans2.errors }}</td>
  			</tr>
  
  			<tr>
    			<td><label for="id_que3">Question 3 *</label></td>
    			<td>:</td>
    			<td>{{ form3.que3 }}</td>
			    <td>{{ form3.que3.errors }}</td>
 			</tr>
 			
 			<tr>
    			<td><label for="id_ans3">Answer 3 *</label></td>
    			<td>:</td>
    			<td>{{ form3.ans3 }}</td>
    			<td>{{ form3.ans3.errors }}</td>
  			</tr>
  
  			<tr>
    			<td><label for="id_username">Username (for login) *</label></td>
    			<td>:</td>
    			<td>{{ form2.username }}</td>
    			<td>{{ form2.username.errors }}</td>
  			</tr>
  			
  			<tr>
    			<td><label for="id_password">Password (for login) *</label></td>
    			<td>:</td>
    			<td>{{ form2.password }}</td>
    			<td>{{ form2.password.errors }}</td>
  			</tr>
  			
  			<tr>
    			<td><label for="id_repassword">Confirm Password *</label></td>
    			<td>:</td>
    			<td>{{ form2.repassword }}</td>
    			<td>{{ form2.repassword.errors }}</td>
  			</tr>
		</table>

		<p><input type="submit" value="sign(me)up" name="keypress" class="buttons" /></p>
	</p>
</form>
{% endblock %}

passwordreset/templates/reset_password.htm
{% extends "base.html" %}

{% block title %}new member signup{% endblock %}

{% block page_id %}- Signup Page{% endblock %}

{% block content %}
<form action="" method="POST">
{% csrf_token %}
	<p>
		{{ form1.non_field_errors }}
		{{ form2.non_field_errors }}
		
		<table width="100%" border="0">
  			<tr>
    			<td width="11%"><label for="id_password">Password (for login) *</label></td>
    			<td width="1%" >:</td>
    			<td width="21%">{{ form.password }}</td>
    			<td width="67%">{{ form.password.errors }}</td>
  			</tr>
  			
  			<tr>
    			<td><label for="id_repassword">Confirm Password *</label></td>
    			<td>:</td>
    			<td>{{ form.repassword }}</td>
    			<td>{{ form.repassword.errors }}</td>
  			</tr>
		</table>

		<p><input type="submit" value="reset password" name="keypress" class="buttons" /></p>
	</p>
</form>
{% endblock %}